# ESLint v7.23.0

parser: '@babel/eslint-parser'

parserOptions:
  ecmaFeatures:
    impliedStrict: true
  ecmaVersion: 12
  sourceType: module

extends:
  - eslint:recommended

env:
  es2021: true

reportUnusedDisableDirectives: true

rules:
  accessor-pairs: warn
  array-callback-return: warn
  block-scoped-var: warn
  class-methods-use-this: off
  default-case: warn
  default-case-last: warn
  default-param-last: warn
  eqeqeq: warn
  eol-last: warn
  max-depth: warn
  max-nested-callbacks:
    - warn
    - 3
  max-params: warn
  max-statements: off
  max-statements-per-line:
    - warn
    - max: 2
  new-cap: warn
  no-alert: warn
  no-array-constructor: warn
  no-bitwise: warn
  no-caller: error
  no-confusing-arrow: warn
  no-console:
    - warn
    - allow:
      - error
      - info
      - time
      - timeEnd
      - warn
  no-constructor-return: warn
  no-duplicate-imports:
    - warn
    - includeExports: true
  no-empty:
    - error
    - allowEmptyCatch: false
  no-empty-function: error
  no-eq-null: error
  no-extend-native: warn
  no-extra-bind: warn
  no-extra-label: warn
  no-eval: warn
  no-fallthrough:
    - error
    - commentPattern: /falls?\s?through/i
  no-implicit-coercion: warn
  no-implicit-globals: warn
  no-implied-eval: warn
  no-invalid-this: warn
  no-iterator: error
  no-label-var: warn
  no-lone-blocks: warn
  no-lonely-if: warn
  no-loop-func: warn
  no-loss-of-precision: error
  no-magic-numbers:
    - warn
    - ignoreArrayIndexes: true
      ignoreDefaultValues: true
      ignore:
      - -1
      - 0
      - 1
      - 2
      - 60
      - 200
      - 201
      - 204
      - 207
      - 302
      - 304
      - 400
      - 401
      - 403
      - 404
      - 405
      - 408
      - 409
      - 410
      - 412
      - 413
      - 422
      - 429
      - 449
      - 500
      - 503
  no-mixed-operators: warn
  no-negated-condition: warn
  no-new: warn
  no-new-func: warn
  no-new-wrappers: warn
  no-nonoctal-decimal-escape: error
  no-octal-escape: error
  no-param-reassign: warn
  no-promise-executor-return: warn
  no-proto: error
  no-return-assign:
    - warn
    - always
  no-return-await: warn
  no-script-url: warn
  no-self-compare: error
  no-shadow:
    - warn
    - builtinGlobals: true
      hoist: all
      allow:
        - cb
        - done
        - err
        - error
        - ev
        - event
        - name
        - resolve
        - reject
        - Text
  no-tabs: warn
  no-template-curly-in-string: warn
  no-throw-literal: error
  no-trailing-spaces: off
  no-undef:
    - error
    - typeof: true
  no-undefined: warn
  no-unmodified-loop-condition: warn
  no-unneeded-ternary: warn
  no-unreachable-loop: error
  no-unsafe-optional-chaining: error
  no-unused-expressions: error
  no-use-before-define:
    - warn
    - classes: false
      functions: false
  no-useless-backreference: error
  no-useless-call: error
  no-useless-computed-key: warn
  no-useless-concat: warn
  no-useless-constructor: warn
  no-useless-rename: warn
  no-useless-return: warn
  no-var: warn
  no-warning-comments: warn
  prefer-const: error
  prefer-numeric-literals: warn
  prefer-promise-reject-errors: warn
  prefer-exponentiation-operator: warn
  prefer-rest-params: warn
  prefer-spread: warn
  prefer-template: warn
  quote-props:
    - warn
    - as-needed
  require-atomic-updates: warn
  require-await: warn
  require-unicode-regexp: warn
  semi: error
  symbol-description: error
  unicode-bom: error
  vars-on-top: warn
  yoda:
    - warn
    - never
    - exceptRange: true
