plugins:
  - chai-friendly

extends:
  - plugin:cypress/recommended

env:
  shared-node-browser: true

globals:
  app:  true

overrides:
  - files:
      - '**/*.test.js'
      - '**/*.unit.js'
    rules:
      func-names:            off
      prefer-arrow-callback: off
      max-nested-callbacks:  off
      no-magic-numbers:      off
      no-param-reassign:     off

rules:
  no-unused-expressions: off
  chai-friendly/no-unused-expressions: error
