name: deploy

on:
  release:
    types:
      - published
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:

  build_and_deploy:
    if:      github.event_name == 'release' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name:    Build & Deploy
    steps:

      - name: checkout repo
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  ${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        if:   steps.cache.outputs.cache-hit != 'true'
        run:  npm ci

      - name: build app
        run:  npm run build

      - name: deploy to Microsoft Azure
        id:   builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_OCEAN_09018B510 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/dist" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          skip_app_build: true # Use a custom build step (above)
          ###### End of Repository/Build Configurations ######

      - name: deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if:   github.event_name == 'release'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir:  ./docs

  close_pull_request_job:
    if:      github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name:    Close Pull Request
    steps:
      - name: close pull request
        id:   closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLUE_OCEAN_09018B510 }}
          action: "close"
