name: Lighthouse Audit
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: cache Node.js modules
        id:   cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  ${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run:  npm install

      - name: build app
        run:  npm run build

      - name: run Lighthouse audit
        run:  lhci autorun