name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  run-tests:
    name:    run tests
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run multiple copies of the current job in parallel
        containers: [1, 2]

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: cache Node.js modules
        id:   cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key:  ${{ hashFiles('**/package-lock.json') }}

      - name: install dependencies
        run:  npm install
      
      - name: run stop-only test
        run:  npm run stop-only

      - name: build app
        run:  npm run build
      
      - name: run tests
        run:  npm test
      
      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      # - name: run Cypress E2E tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     config-file:     test/cypress.e2e.json
      #     headless:        true
      #     parallel:        true
      #     record:          true
      #     start:           npm start
      #     wait-on:         'http://localhost:3000'
      #     wait-on-timeout: 10
      #   env:
      #     CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
      #     GITHUB_TOKEN:       ${{secrets.GITHUB_TOKEN}}
